/**
 * `llms.txt` — a machine-readable index of this site for language models.
 *
 * The convention (llmstxt.org) is a single markdown file at the root: a title,
 * a one-line summary, then sections of links with a sentence each. Assistants
 * that fetch a site increasingly look here first rather than crawling and
 * guessing, and what they find is the description WordPress already wrote for
 * each page — so this costs one endpoint and no new prose.
 *
 * WordPress serves one of these at the apex, generated by a plugin. This is the
 * same idea rebuilt from this site's own routes, which matters because the two
 * sites do not have the same URLs: the plugin's file lists `/blog/<slug>/` and
 * apex hosts, both of which are redirects here.
 *
 * Deliberately *not* an `llms-full.txt`. That variant inlines every post body,
 * which for 259 posts is several megabytes of HTML-to-markdown conversion and a
 * dependency this build does not otherwise need. The index is what the crawlers
 * actually read; the bodies are one fetch away from the links below.
 *
 * An endpoint rather than a file in `public/`, for the same reason robots.txt
 * is one: the URLs in it are `SITE_URL`-dependent and a committed static file
 * would name whichever host happened to be current when someone last saved it.
 */
import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { SITE_URL } from '../../scripts/lib/config.mjs';
import { postUrl } from '../data/blog-categories';
import wpPages from '../data/wp-pages.json';

type PageMeta = { title: string; description: string };

/**
 * The marketing pages, discovered from the routes rather than from the page
 * index.
 *
 * `wp-pages.json` holds metadata for 487 mirrored pages, most of which are not
 * routes any more — reading it as the list would advertise several hundred URLs
 * that 404. Globbing `src/pages/*.astro` asks the only question that matters:
 * what does this site actually build?
 */
const ROUTE_FILES = import.meta.glob('./*.astro', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;

/**
 * Routes that are not pages a reader would be sent to.
 *
 * `index` is the site root, already named by the heading and the summary above.
 * A bracketed filename is a dynamic route, not a page — `[...wpRedirect]` is the
 * catch-all that replays WordPress' 301s, and listing it advertises a URL with
 * literal brackets in it.
 */
const NOT_LISTED = new Set(['404', 'index', 'sitemap']);
const isDynamic = (slug: string) => slug.includes('[');

/**
 * A page that only redirects is not a page to send anything to.
 *
 * Two of them are their own file — `finance-and-hr` and
 * `bookings-checkout-discovery-call-book` — and both would otherwise be listed
 * here under a slug-derived title, pointing an assistant at a bounce. Read out
 * of the route source, which is why the glob above is `?raw`: the same test the
 * sitemap filter applies, made from the same evidence.
 */
const isRedirect = (source: string) => source.includes('/Redirect.astro');

/** Yoast's titles all carry the site name; the heading above says it once. */
const stripSuffix = (title: string) => title.replace(/\s*[|–—-]\s*Spenza\s*$/i, '').trim();

/** Title-case a slug, for the handful of pages Yoast never gave a title. */
const fromSlug = (slug: string) =>
  slug
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

/** Descriptions come from HTML attributes and excerpts, so they carry entities. */
const decode = (s: string) =>
  s
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&#8217;|&rsquo;/g, '\u2019')
    .replace(/&#8216;|&lsquo;/g, '\u2018')
    .replace(/&#8220;|&ldquo;/g, '\u201c')
    .replace(/&#8221;|&rdquo;/g, '\u201d')
    .replace(/&#8211;|&ndash;/g, '\u2013')
    .replace(/&#8212;|&mdash;/g, '\u2014')
    .replace(/&nbsp;/g, ' ')
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;|&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();

/**
 * One markdown bullet. The description is optional; the link never is.
 *
 * Titles are decoded as well as descriptions. They come from Yoast's `<title>`,
 * where an apostrophe is `&#039;` and an ampersand is `&amp;` — correct inside
 * an HTML element and wrong in a plain-text file, which is what this is.
 */
function entry(title: string, path: string, description: string): string {
  const line = `- [${stripSuffix(decode(title))}](${SITE_URL}${path})`;
  const d = decode(description);
  return d ? `${line}: ${d}` : line;
}

export const GET: APIRoute = async () => {
  const pages = wpPages as Record<string, PageMeta>;

  const home = pages.index;

  const marketing = Object.entries(ROUTE_FILES)
    .filter(([, source]) => !isRedirect(source))
    .map(([file]) => file.replace(/^\.\//, '').replace(/\.astro$/, ''))
    .filter(slug => !NOT_LISTED.has(slug) && !isDynamic(slug))
    .sort()
    .map(slug => {
      const meta = pages[slug];
      // A route with no mirrored metadata is still a page, and so is one whose
      // Yoast title is the bare site name — three of the demo pages are. Name
      // those from the slug rather than dropping them or listing three
      // identical "Spenza" links, so the index stays complete and legible.
      const given = stripSuffix(decode(meta?.title ?? ''));
      const title = given && given.toLowerCase() !== 'spenza' ? given : fromSlug(slug);
      return entry(title, `/${slug}/`, meta?.description ?? '');
    });

  const posts = await getCollection('posts');
  const byNewest = [...posts].sort(
    (a, b) => b.data.publishedDate.getTime() - a.data.publishedDate.getTime()
  );

  const line = (p: (typeof posts)[number]) =>
    entry(
      p.data.seo.title || p.data.title,
      postUrl(p.data.category, p.data.slug),
      p.data.seo.description || p.data.excerpt
    );

  const articles = byNewest.filter(p => !p.data.isCaseStudy).map(line);
  const caseStudies = byNewest.filter(p => p.data.isCaseStudy).map(line);

  /**
   * A heading with nothing under it is worse than no heading: it tells a reader
   * this site has no case studies, and it has several.
   *
   * `isCaseStudy` comes from a `case-study` tag that no post currently carries,
   * so this section is empty today — the case studies are published as ordinary
   * posts under /spenza-product/. Written as a conditional rather than deleted,
   * because the moment somebody applies that tag in WordPress the section should
   * appear on the next build without anyone having to remember this file.
   */
  const section = (heading: string, lines: string[]) =>
    lines.length ? ['', heading, '', ...lines] : [];

  const body = [
    '# Spenza',
    '',
    `> ${decode(home?.description ?? '')}`,
    '',
    'Spenza is a connectivity-as-a-service platform: launch and run an MVNO,',
    'manage IoT and eSIM connectivity, and control business telecom spend from',
    'one place. Blog posts are grouped by category in the URL',
    '(`/mvno/`, `/esim/`, `/iot/`, `/telecom/`, `/tem/`, `/byod/`,',
    '`/spenza-product/`); the same posts are also listed at /blog/.',
    '',
    ...section('## Pages', marketing).slice(1),
    ...section('## Case studies', caseStudies),
    ...section('## Blog posts', articles),
    '',
  ].join('\n');

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
